bt_navigator:
  ros__parameters:
    global_frame: <tf_prefix>/map
    robot_base_frame: <tf_prefix>/base_link
    odom_topic: <robot_namespace>/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code


bt_task_navigator:
  ros__parameters:
    global_frame: <tf_prefix>/map
    robot_base_frame: <tf_prefix>/base_link
    odom_topic: <robot_namespace>/odom
    bt_loop_duration: 500
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["run_tasks",]
    run_tasks:
      plugin: "project11_navigation::TaskNavigator"
      debug: false
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    plugin_lib_names: 
      - project11_navigation_baxevani_controller_bt_node
      - project11_navigation_clear_path_bt_node
      - project11_navigation_crabbing_path_follower_bt_node
      - project11_navigation_debug_blackboard_bt_node
      - project11_navigation_generate_plan_bt_node
      - project11_navigation_get_task_data_double_bt_node
      - project11_navigation_get_task_data_string_bt_node
      - project11_navigation_get_sub_tasks_bt_node
      - project11_navigation_hover_action_bt_node
      - project11_navigation_hover_cancel_node_bt_node
      - project11_navigation_multibeam_coverage_action_bt_node
      - project11_navigation_predict_stopping_pose_bt_node
      - project11_navigation_set_pose_from_task_bt_node
      - project11_navigation_set_task_done_bt_node
      - project11_navigation_set_trajectory_from_task_bt_node
      - project11_navigation_task_list_updater_bt_node
      - project11_navigation_update_current_segment_bt_node
      - project11_navigation_update_current_task_bt_node
      - project11_navigation_visualize_trajectory_bt_node
      - project11_navigation_all_tasks_done_bt_node
      - project11_navigation_goal_reached_bt_node
      - project11_navigation_plan_needed_bt_node


    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
      - hover_error_code



controller_server:
  ros__parameters:
    controller_frequency: 5.0
    costmap_update_timeout: 1.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath", "MPPI"]
    use_realtime_priority: false
    enable_stamped_cmd_vel: true

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 4.5
      yaw_goal_tolerance: 5.0
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      allow_reversing: false
      approach_velocity_scaling_dist: 10.0
      cancel_deceleration: 3.2
      cost_scaling_dist: 100.0
      cost_scaling_gain: 0.5
      curvature_lookahead_dist: 7.5
      desired_linear_vel: 2.75
      interpolate_curvature_after_goal: true
      lookahead_dist: 5.0
      lookahead_time: 3.5
      max_allowed_time_to_collision_up_to_carrot: 3.5
      max_angular_accel: 0.45
      max_lookahead_dist: 20.0
      max_robot_pose_search_dist: 124.875
      min_approach_linear_velocity: 0.25
      min_lookahead_dist: 3.0
      regulated_linear_scaling_min_radius: 5.0
      regulated_linear_scaling_min_speed: 0.5
      rotate_to_heading_angular_vel: 0.5
      rotate_to_heading_min_angle: 0.5
      transform_tolerance: 0.1
      use_cancel_deceleration: true
      use_collision_detection: true
      use_cost_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: true
      use_regulated_linear_velocity_scaling: true
      use_rotate_to_heading: false
      use_velocity_scaled_lookahead_dist: true

    MPPI:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.2
      batch_size: 15000
      ax_max: 0.8
      ax_min: -0.7
      ay_max: 0.0
      az_max: 0.2
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.5
      vx_max: 2.75
      vx_min: -0.15
      vy_max: 0.0
      wz_max: 0.45
      iteration_count: 1
      prune_distance: 25.0
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "Ackermann"
      visualize: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 25
        time_step: 6
      AckermannConstraints:
        min_turning_r: 5.0
      critics: [
        "ConstraintCritic", "CostCritic", "GoalCritic",
        "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
        "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 5.0
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 5.0
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        threshold_to_consider: 1.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 5.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 5.0
        offset_from_furthest: 10
        use_path_orientations: true
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 5.0
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5
        offset_from_furthest: 4
        threshold_to_consider: 10.0
        max_angle_to_furthest: 1.0
        mode: 0
      # TwirlingCritic:
      #   enabled: true
      #   twirling_cost_power: 1
      #   twirling_cost_weight: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: <tf_prefix>/odom
      robot_base_frame: <tf_prefix>/base_link
      rolling_window: true
      width: 350
      height: 350
      resolution: 0.5
      footprint: "[[1.0, 0], [0.0, 0.3], [-0.5, 0.3], [-0.5, -0.3], [0.0, -0.3], [1.0, 0]]"
      plugins: ["chart_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.05
        inflation_radius: 150.0
      chart_layer:
        plugin: "s57_layer::S57Layer"
        enabled: True
        minimum_depth: 0.1
        maximum_caution_depth: 1.0
        overhead_clearance: 2.0
        update_timeout: 0.15


      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: <tf_prefix>/map
      robot_base_frame: <tf_prefix>/base_link
      robot_radius: 1.5
      footprint: "[[1.0, 0], [0.0, 0.3], [-0.5, 0.3], [-0.5, -0.3], [0.0, -0.3], [1.0, 0]]"
      resolution: 1.0
      track_unknown_space: true
      rolling_window: true
      width: 5000
      height: 5000
      plugins: ["chart_layer", "inflation_layer"]
      chart_layer:
        plugin: "s57_layer::S57Layer"
        enabled: True
        minimum_depth: 0.1
        maximum_caution_depth: 1.0
        overhead_clearance: 2.0
        update_timeout: 0.75
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.05
        inflation_radius: 150.0
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 0.2
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 5.0
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      tolerance: 1.5
      allow_primitive_interpolation: true
      allow_unknown: true
      change_penalty: 0.5
      cost_penalty: 10.0
      minimum_turning_radius: 1.0
      debug_visualizations: false
      max_iterations: -1
      max_on_approach_iterations: -1
      max_planning_time: 5.0
      analytic_expansion_max_length: 25.0
      angle_quantization_bins: 72
      lookup_table_size: 55.0
      non_straight_penalty: 1.1
      use_quadratic_cost_penalty: false


smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait", "hover"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    hover:
      plugin: "project11_navigation::Hover"
      minimum_radius: 2.5
      maximum_radius: 10.0
      maximum_speed: 1.0
      maximum_rotation_speed: 0.75
      deceleration: -0.45
      generate_visualization: true

    local_frame: <tf_prefix>/odom
    global_frame: <tf_prefix>/map
    robot_base_frame: <tf_prefix>/base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    enable_stamped_cmd_vel: true

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 10.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    max_velocity: [2.75, 0.0, 0.45]
    min_velocity: [-0.5, 0.0, -0.45]
    max_accel: [0.8, 0.0, 0.2]
    max_decel: [-0.45, 0.0, -0.2]
    odom_topic: <robot_namespace>/odom
    odom_duration: 0.5
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    enable_stamped_cmd_vel: true

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: <tf_prefix>/odom
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "piloting_mode/autonomous/cmd_vel"
    enable_stamped_cmd_vel: true
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: <tf_prefix>/base_link
    fixed_frame: <tf_prefix>/odom
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    # docks: ['home_dock']  # Input your docks here
    # home_dock:
    #   type: 'simple_charging_dock'
    #   frame: map
    #   pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3

